[package]
name = "cargo-trend"
version = "0.1.0"
authors = ["dalance@gmail.com"]
repository = "https://github.com/dalance/cargo-trend"
keywords = []
categories = []
license = "MIT"
readme = "README.md"
description = ""
edition = "2018"

[[bin]]
name = "cargo-trend"
path = "src/main.rs"

[[bin]]
name = "update_db"
path = "src/update_db.rs"

[dependencies]
chrono       = {version = "0.4", features = ["serde"]}
crates-index = "0.13"
flate2       = "1.0"
git2         = "0.10"
failure      = "0.1"
plotters     = "0.2"
random_color = "0.4"
serde        = {version = "1.0", features = ["derive"]}
serde_json   = "1.0"
tempfile     = "3.1"
