name: Update samples

on:
  schedule:
  - cron: 0 3 * * SUN

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run
      run: |
        cargo run -- trend --output samples/error.svg failure error-chain quick-error snafu err-derive anyhow thiserror
        cargo run -- trend --relative --output samples/error_relative.svg failure error-chain quick-error snafu err-derive anyhow thiserror
        cargo run -- trend --output samples/arg.svg clap structopt docopt argparse getopts
        cargo run -- trend --relative --output samples/arg_relative.svg clap structopt docopt argparse getopts
        cargo run -- trend --output samples/term.svg ansi_term termcolor term termion colored console
        cargo run -- trend --relative --output samples/term_relative.svg ansi_term termcolor term termion colored console
        cargo run -- trend --xsize 600 --ysize 400 --output samples/top5.svg --top 5 --duration 4
        cargo run -- trend --xsize 600 --ysize 400 --relative --output samples/top5_relative.svg --top 5 --duration 4

    - name: Commit
      uses: EndBug/add-and-commit@v2.1.0
      with:
        author_name: dalance
        author_email: dalance@gmail.com
        message: "Update samples"
        path: "./samples"
        pattern: "*.svg"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

