name: Update DB

on:
  schedule:
  - cron: 0 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
    - uses: Swatinem/rust-cache@v1
    - name: Run
      run: cargo run --release -- trend --update db_v2/db.gz

    - name: Commit
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: "Update db"
        add: "./db_v2/db*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

