name: Update DB

on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
    - uses: Swatinem/rust-cache@v1
    - name: Run
      run: cargo run --release -- trend --update db_v3

    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "Update db"
        add: "./db_v3/db*"
        fetch: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
