name: Update DB

on:
  schedule:
  - cron: 0 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: cargo run --release -- trend --update db_v2/db.gz

    - name: Commit
      uses: EndBug/add-and-commit@v2.1.0
      with:
        author_name: dalance
        author_email: dalance@gmail.com
        message: "Update db"
        path: "./db_v2"
        pattern: "db*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

